### ISSUE TITLE
Pre-release identifiers

### ISSUE THREAD

**Issue by tanner0101** [amzn/smoke-aws#41]
I'm running into some strange SPM errors when using `.branch("2.25.35.alpha.1")`. These go away if I specify a specific revision. In this case, `.revision("43b6b5...")`. I think this is due to how SPM treats branches differently than revisions or tagged versions. 

If this package used standardized semver pre-release identifiers, then people be able to depend on alpha versions without using `.branch`. For example, if the release were tagged as `2.0.0-alpha.1`, one could do:

```swift
.package(url: "https://github.com/amzn/smoke-aws.git", from: "2.0.0-alpha")
```

This has the added benefit of automatically opting into later alphas, betas, and the final release when one does `swift package update`.

**Comment by tachyonics** [comment]
Thanks @tanner0101, I didn't realise SPM supported pre-release tags this way. I have tagged a `2.0.0-alpha.2` version. Let me know if you need anything else or have any issues.

**Comment by tanner0101** [comment]
@tachyonics thanks! That fixed my issue.
